apiVersion: v1
kind: ConfigMap
metadata:
  name: lms-config
  namespace: lms
data:
  SPRING_PROFILES_ACTIVE: "docker"
  KEYCLOAK_AUTH_SERVER_URL: "http://keycloak:8080"
  SPRING_REDIS_HOST: "redis"
  SPRING_REDIS_PORT: "6379"
  SPRING_KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
  SPRING_ELASTICSEARCH_URIS: "http://elasticsearch:9200"
  MINIO_ENDPOINT: "http://minio:9000"
